import { DataSource } from 'typeorm';
import { config } from 'dotenv';

config();

const dbType = (process.env.DB_TYPE || 'postgres').toLowerCase();
const seedEnabled = process.env.SEED_ENABLED === 'true';

function buildDataSource(): DataSource {
  if (dbType === 'oracle') {
    return new DataSource({
      type: 'oracle',
      host: process.env.DB_HOST || 'localhost',
      port: parseInt(process.env.DB_PORT || '1521'),
      username: process.env.DB_USERNAME,
      password: process.env.DB_PASSWORD,
      serviceName: process.env.DB_SERVICE_NAME,
      synchronize: false,
      logging: false,
    });
  }
  return new DataSource({
    type: 'postgres',
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432'),
    username: process.env.DB_USERNAME || 'postgres',
    password: process.env.DB_PASSWORD || 'password',
    database: process.env.DB_NAME || 'postgres',
    synchronize: false,
    logging: false,
  });
}

async function tableExists(ds: DataSource, name: string): Promise<boolean> {
  if (dbType === 'oracle') {
    const [{ CNT }] = await ds.query(
      `SELECT COUNT(*) AS CNT FROM user_tables WHERE table_name = :1`,
      [name.toUpperCase()],
    );
    return Number(CNT) > 0;
  }
  const [{ cnt }] = await ds.query(
    `SELECT COUNT(*) AS cnt
     FROM information_schema.tables
     WHERE table_schema = 'public' AND table_name = $1`,
    [name.toLowerCase()],
  );
  return Number(cnt) > 0;
}

async function hasSeedData(ds: DataSource): Promise<boolean> {
  if (!(await tableExists(ds, 'departments'))) return false;
  if (dbType === 'oracle') {
    const [{ CNT }] = await ds.query(`SELECT COUNT(*) AS CNT FROM departments`);
    return Number(CNT) > 0;
  }
  const [{ cnt }] = await ds.query(`SELECT COUNT(*) AS cnt FROM departments`);
  return Number(cnt) > 0;
}

async function createTables(ds: DataSource): Promise<void> {
  if (dbType === 'oracle') {
    if (!(await tableExists(ds, 'departments'))) {
      await ds.query(`
        CREATE TABLE departments (
          id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name     VARCHAR2(100) NOT NULL,
          location VARCHAR2(100)
        )
      `);
    }
    if (!(await tableExists(ds, 'employees'))) {
      await ds.query(`
        CREATE TABLE employees (
          id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          first_name VARCHAR2(50),
          last_name  VARCHAR2(50),
          email      VARCHAR2(100),
          salary     NUMBER(10, 2),
          dept_id    NUMBER REFERENCES departments(id)
        )
      `);
    }
  } else {
    await ds.query(`
      CREATE TABLE IF NOT EXISTS departments (
        id       SERIAL PRIMARY KEY,
        name     VARCHAR(100) NOT NULL,
        location VARCHAR(100)
      )
    `);
    await ds.query(`
      CREATE TABLE IF NOT EXISTS employees (
        id         SERIAL PRIMARY KEY,
        first_name VARCHAR(50),
        last_name  VARCHAR(50),
        email      VARCHAR(100),
        salary     DECIMAL(10, 2),
        dept_id    INTEGER REFERENCES departments(id)
      )
    `);
  }
}

async function clearData(ds: DataSource): Promise<void> {
  if (dbType === 'oracle') {
    // Delete in FK order: children first, then parent
    await ds.query(`DELETE FROM employees`);
    await ds.query(`DELETE FROM departments`);
  } else {
    await ds.query(`TRUNCATE TABLE employees, departments RESTART IDENTITY CASCADE`);
  }
}

async function insertData(ds: DataSource): Promise<void> {
  if (dbType === 'oracle') {
    await ds.query(`
      INSERT ALL
        INTO departments (name, location) VALUES ('IT', 'New York')
        INTO departments (name, location) VALUES ('HR', 'London')
        INTO departments (name, location) VALUES ('Sales', 'San Francisco')
      SELECT 1 FROM DUAL
    `);
    // Reference departments by name to avoid relying on hardcoded IDs
    const employees = [
      { first: 'John',    last: 'Doe',     email: 'john@example.com',    salary: 60000, dept: 'IT' },
      { first: 'Jane',    last: 'Smith',   email: 'jane@example.com',    salary: 75000, dept: 'IT' },
      { first: 'Alice',   last: 'Johnson', email: 'alice@example.com',   salary: 50000, dept: 'HR' },
      { first: 'Bob',     last: 'Brown',   email: 'bob@example.com',     salary: 45000, dept: 'Sales' },
      { first: 'Charlie', last: 'Davis',   email: 'charlie@example.com', salary: 80000, dept: 'IT' },
    ];
    for (const e of employees) {
      await ds.query(
        `INSERT INTO employees (first_name, last_name, email, salary, dept_id)
         SELECT :1, :2, :3, :4, id FROM departments WHERE name = :5`,
        [e.first, e.last, e.email, e.salary, e.dept],
      );
    }
  } else {
    await ds.query(`
      INSERT INTO departments (name, location) VALUES
        ('IT', 'New York'),
        ('HR', 'London'),
        ('Sales', 'San Francisco')
    `);
    await ds.query(`
      INSERT INTO employees (first_name, last_name, email, salary, dept_id) VALUES
        ('John',    'Doe',     'john@example.com',    60000, 1),
        ('Jane',    'Smith',   'jane@example.com',    75000, 1),
        ('Alice',   'Johnson', 'alice@example.com',   50000, 2),
        ('Bob',     'Brown',   'bob@example.com',     45000, 3),
        ('Charlie', 'Davis',   'charlie@example.com', 80000, 1)
    `);
  }
}

async function seed(): Promise<void> {
  const ds = buildDataSource();
  await ds.initialize();

  try {
    if (!seedEnabled && (await hasSeedData(ds))) {
      console.log('Seed skipped: data already exists. Set SEED_ENABLED=true to force re-seed.');
      return;
    }

    console.log(`Seeding database (type: ${dbType})...`);
    await createTables(ds);
    await clearData(ds);
    await insertData(ds);
    console.log('Seeding complete!');
  } finally {
    await ds.destroy();
  }
}

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
